### ISSUE TITLE
How to use threat intelligence feeds

### ISSUE THREAD

**Issue by setu-improbable** [GoogleCloudPlatform/terraform-google-cloud-armor#10]
Can you please add an example to show how we can use Threat Intelligence feeds using Terraform? 
For example, an equivalent of  "evaluateThreatIntelligence('iplist-known-malicious-ips')" @imrannayer

**Comment by imrannayer** [comment]
Can u try this. Just pass iplist-known-malicious-ips in feed. 

https://github.com/GoogleCloudPlatform/terraform-google-cloud-armor#threat_intelligence_rules
