### ISSUE TITLE
Does not update preconfigured_waf_config_exclusions when exclusions added

### ISSUE THREAD

**Issue by spawar-apex** [GoogleCloudPlatform/terraform-google-cloud-armor#121]
Hi,

WE have encountered a problem when updating/.modifying the `preconfigured_waf_config_exclusions` in our Cloud Armor configurations.

We have already deployed the new module updates as per new enhancement request raised by @Nathan01110011. Recently, We are facing an issue when updating Cloud armor exclusions configuration via IaC.

When we are trying to update ad `rule_ids`, `request_query_param` or `request_cookie`, Terraform does not identify the updates in the rules and when terraform perform `tf plan`, it says

`No changes. Your infrastructure matches the configuration. Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.`

This is a weird behaviour we have seen. it does show custom rules and other rules but anything gets modified within `preconfigured_waf_config_exclusions` doesnt get picked by tf plan.

Could anyone please share some thoughts here?

**Comment by imrannayer** [comment]
@spawar-apex thats exactly what you need to do. COmment out the `preconfigured_waf_config_exclusion` and execute `terraform apply`. Then add `preconfigured_waf_config_exclusions` block and execute `terraform apply`. I am going to remove label `Big` as it is working as expected.
