### ISSUE TITLE
add "scope" input for cloud armor

### ISSUE THREAD

**Issue by heroes1412** [GoogleCloudPlatform/terraform-google-cloud-armor#124]
in console, i can switch scope between "Global" vs "Regional", but in this module, i do not find any input like that

**Comment by imrannayer** [comment]
@heroes1412 It is not a parameter in TF like it is on console. There are two different resources `google_compute_security_policy` and `google_compute_region_security_policy`. Root module can create cloud armor global security policy for backend and edge. I am working on a sub-module which will create regional backend security policy. It is already tracked in feature request #62
