### ISSUE TITLE
No support for policy type  CLOUD_ARMOR_NETWORK

### ISSUE THREAD

**Issue by mspoonauer** [GoogleCloudPlatform/terraform-google-cloud-armor#24]
One of the requirements for enabling advanced DDoS protection is to use the security policy type `CLOUD_ARMOR_NETWORK`.

When I try to use that type, though, I get the following error from the Google provider, whether I use `google` or `google-beta`:

```
-Error: expected type to be one of [CLOUD_ARMOR CLOUD_ARMOR_EDGE CLOUD_ARMOR_INTERNAL_SERVICE], got CLOUD_ARMOR_NETWORK

  on waf_enforced_security_policy.tf line 3, in resource "google_compute_security_policy" "policy-waf-enforced":
   3:   type = "CLOUD_ARMOR_NETWORK"
```

**Comment by imrannayer** [comment]
@mspoonauer Module does not restrict value for this variable. It is not supported by the provider. I have created two issues for the provider which will resolve this issue.

https://github.com/hashicorp/terraform-provider-google/issues/13978

https://github.com/hashicorp/terraform-provider-google/issues/13979
