### ISSUE TITLE
Optional variable can't be used when i enables it as an experiments in terraform block

### ISSUE THREAD

**Issue by sarath-s-kumar** [GoogleCloudPlatform/terraform-google-cloud-armor#3]
Error: Invalid type specification
│
│   on variables.tf line 45, in variable "pre_configured_rules":
│   45:     preview                 = optional(bool, false)
│
│ Optional attribute modifier expects only one argument: the attribute type.

**Comment by imrannayer** [comment]
Are you using terraform version 1.3+? You dont need to enable experiment for 1.3 as the feature is part of 1.3.

**Comment by MaKsaw** [comment]
From the readme "If you find incompatibilities using Terraform >=0.13, please open an issue."

## Terraform version
0.14.11

```
terraform init
```

```
Warning: Experimental feature "module_variable_optional_attrs" is active

  on versions.tf line 3, in terraform:
   3:   experiments      = [module_variable_optional_attrs]

Experimental features are subject to breaking changes in future minor or patch
releases, based on feedback.

If you have feedback on the design of this feature, please open a GitHub issue
to discuss it.
```

**Comment by imrannayer** [comment]
I would recommend opening issue for [terraform](https://github.com/hashicorp/terraform/issues). If this experimental feature will work in 0.14 as it is in 1.3.

https://github.com/hashicorp/terraform/issues

**Comment by MaKsaw** [comment]
@imrannayer - Let me elaborate.

I have the below in my root module.
```
terraform {
  required_version = ">= 0.14"
  experiments      = [module_variable_optional_attrs]
...
}
``` 
I can also confirm that `module_variable_optional_attrs` experimental feature _does work_ with v0.14.11 in other areas in my codebase.

According to terraform, `experiments` must be enabled _per module basis_ - [reference](https://developer.hashicorp.com/terraform/language/settings#experimental-language-features) 

Therefore `experiments  = [module_variable_optional_attrs]` should be set on the `terraform  {}` block within the module source code as well - which I cannot do as the module consumer. 
So, can `module_variable_optional_attrs` be included into the module source?

Similar issue is discussed [here](https://github.com/hashicorp/terraform/issues/24147#issuecomment-587961724)

**Comment by imrannayer** [comment]
Setting `experiments` on a stable release does not work any more - [ref](https://github.com/hashicorp/terraform/issues/31355).
