### ISSUE TITLE
Add preconfigured_waf_config block will be added to the module?

### ISSUE THREAD

**Issue by maksymsereda** [GoogleCloudPlatform/terraform-google-cloud-armor#33]
Hi,
Is there a plan to add [preconfigured_waf_config](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_security_policy#preconfigured_waf_config) block to the module?

**Comment by maksymsereda** [comment]
Hi @imrannayer,
I would appreciate any info related to this request. Is it will be implemented? If so, do you know any terms?

**Comment by maksymsereda** [comment]
@imrannayer from my point of view the multiple exclusion blocks are not needed. I used multiple request_header, request_cookie, request_uri and request_query_param in a single exclusion block

**Comment by imrannayer** [comment]
@maksymsereda will the operator be unique in repeated `request_header` block? Is it possible to have something like this?

```
      request_cookie {
          operator = "STARTS_WITH"
          value    = "xyz"
      }
      request_cookie {
          operator = "STARTS_WITH"
          value    = "abc"
      }
```

**Comment by maksymsereda** [comment]
@imrannayer hm... not sure, IMHO it should be one unique request_cookie per exclusion block

**Comment by imrannayer** [comment]
@maksymsereda can you check [example](https://github.com/GoogleCloudPlatform/terraform-google-cloud-armor/pull/34/files#diff-feb22abda999928f3d638fc72f83a1af9c949e7e1fde5bdf6a88962f4741224b) in #34 if it looks fine?

**Comment by maksymsereda** [comment]
@imrannayer yes, as for me that fulfill the requirements

**Comment by imrannayer** [comment]
@maksymsereda code is merged to main repo. It will be while before 1.0 will be released. In the meantime you can point your code directly to git. 
I coded to allow multiple block with same operator. See [example](https://github.com/GoogleCloudPlatform/terraform-google-cloud-armor/blob/b43cfc930920136113dadc5a9a4eab09fd857526/examples/simple-example/main.tf#L59)
