### ISSUE TITLE
advanced_options_config block is not supported for CLOUD_ARMOR_EDGE

### ISSUE THREAD

**Issue by nhu-nguyen27** [GoogleCloudPlatform/terraform-google-cloud-armor#38]
This advanced_options_config block is only supported for CLOUD_ARMOR type. 
```
advanced_options_config {
    json_parsing = var.json_parsing
    log_level    = var.log_level
    dynamic "json_custom_config" {
      for_each = var.json_parsing == "STANDARD" && length(var.json_custom_config_content_types) > 0 ? ["json_custom_config"] : []
      content {
        content_types = var.json_custom_config_content_types
      }
    }
  }
```

I'm getting the following error when I try to use this module to setup a security policy for CLOUD_ARMOR_EDGE
│ Error: Error creating SecurityPolicy: googleapi: Error 400: Invalid value for field 'resource.advancedOptionsConfig': '{  "jsonCustomConfig": {  }}'. Advanced options for Cloud Armor are currently only supported for security policies with CLOUD_ARMOR type., invalid

I've try to passed in null values for those variables, but its not skipping that block. It's still trying to provision it.

**Comment by imrannayer** [comment]
@nhu-nguyen27 can u plz post an example code for edge policy so I can also add a test for it.

**Comment by nhu-nguyen27** [comment]
Here's how I'm using the module. I'm trying to use CLOUD_ARMOR_EDGE since I want to apply this policy to GCS backend

`module "edge_security_policy" {
  source = "GoogleCloudPlatform/cloud-armor/google"

  project_id                           = var.gcp_project_id
  name                                 = "geolocation-allowlist"
  description                          = "Only certain regions can access"
  default_rule_action                  = "deny(403)"
  type                                 = "CLOUD_ARMOR_EDGE"
  layer_7_ddos_defense_enable          = true
  layer_7_ddos_defense_rule_visibility = "STANDARD"
  # these parameters can only be enable in Advanced options for security policies with CLOUD_ARMOR type
  # trying to set these to null to bypass advanced_options_config block
  #json_parsing                         = null
  #log_level                            = null
  #json_custom_config_content_types =  []
  
  custom_rules = {
    allow_specific_regions = {
      action   = "allow"
      priority = 1
      # prod then allow US 
      # non-prod then allow US and Canada
      description = var.env == "production" ? "Only allow from US  : "Only allow from US, Canada"
      expression  = var.env == "production" ? "origin.region_code == 'US' || 'CA'" :   "origin.region_code == 'US' || origin.region_code == 'CA'"
    }
  }
}`

**Comment by imrannayer** [comment]
@nhu-nguyen27 Issue will be fixed with PR #39. `adaptive_protection_config` block is also not supported for edge policies. You can remove `layer_7_ddos_defense_enable` from your code. Module will ignore this value if policy type is set to `CLOUD_ARMOR_EDGE`. Thanks for the example.

**Comment by nhu-nguyen27** [comment]
nope, that didnt work, its still taking in default values and still trying to setup adaptive_protection_config block

my code:
```
module "edge_security_policy" {
  source = "GoogleCloudPlatform/cloud-armor/google"

  project_id                           = var.gcp_project_id
  name                                 = "geolocation-allowlist"
  description                          = "Only certain regions can access"
  default_rule_action                  = "deny(403)"
  type                                 = "CLOUD_ARMOR_EDGE"
  layer_7_ddos_defense_rule_visibility = "STANDARD"
  
  custom_rules = {
    allow_specific_regions = {
      action   = "allow"
      priority = 1
      # prod then allow US 
      # non-prod then allow US and Canada
      description = var.env == "production" ? "Only allow from US  : "Only allow from US, Canada"
      expression  = var.env == "production" ? "origin.region_code == 'US'" :   "origin.region_code == 'US' || origin.region_code == 'CA'"
    }
  }
}

Terraform plan
```
# module.rx2.module.edge_security_policy.google_compute_security_policy.policy will be created
  + resource "google_compute_security_policy" "policy" {
      + description = "Only certain regions can access"
      + fingerprint = (known after apply)
      + id          = (known after apply)
      + name        = "geolocation-allowlist"
      + project     = "staging-service"
      + self_link   = (known after apply)
      + type        = "CLOUD_ARMOR_EDGE"

      + adaptive_protection_config {

          + layer_7_ddos_defense_config {
              + enable          = true
              + rule_visibility = "STANDARD"
            }
        }

      + advanced_options_config {
          + json_parsing = "DISABLED"
          + log_level    = "NORMAL"

          + json_custom_config {
              + content_types = (known after apply)
            }
        }

      + rule {
          + action      = "allow"
          + description = "Only allow from US, Canada"
          + preview     = false
          + priority    = 1

          + match {

              + expr {
                  + expression = "origin.region_code == 'CA' || origin.region_code == 'US'"
                }
            }
        }
      + rule {
          + action      = "deny(403)"
          + description = "Default rule, higher priority overrides it"
          + preview     = (known after apply)
          + priority    = 2147483647

          + match {
              + versioned_expr = "SRC_IPS_V1"

              + config {
                  + src_ip_ranges = [
                      + "*",
                    ]
                }
            }
        }
    }
    
    Here message:
    ```
│ Error: Error creating SecurityPolicy: googleapi: Error 400: Invalid value for field 'resource.advancedOptionsConfig': '{  "jsonParsing": "DISABLED",  "logLevel": "NORMAL",  "jsonCustomConfig": {  }}'. Advanced options for Cloud Armor are currently only supported for security policies with CLOUD_ARMOR type., invalid
│
```

Looks like its not really setting variables in adaptive_protection_config block to null but using default values from json_parsing, log_level, and json_custom_config_content_types

**Comment by imrannayer** [comment]
Wait for the PR merge. PR review is needed.

**Comment by nhu-nguyen27** [comment]
@imrannayer any ETA on when the PR #39 will get review and merged to main?

**Comment by imrannayer** [comment]
@nhu-nguyen27 done. If it is urgent you can access updated module by pointing to main branch directly. It will be available through terraform registry after the release.

**Comment by nhu-nguyen27** [comment]
@imrannayer its working now, thank you so much for updating the module!
