### ISSUE TITLE
Variable layer_7_ddos_defense_enable is marked as optional but is not

### ISSUE THREAD

**Issue by tanguynicolas** [GoogleCloudPlatform/terraform-google-cloud-armor#49]
Hello,

I got this error:
```
│ Error: Operation failed
│ 
│   on .terraform/modules/cloud-armor/main.tf line 458, in resource "google_compute_security_policy" "policy":
│  458:     for_each = var.layer_7_ddos_defense_enable && var.type != "CLOUD_ARMOR_EDGE" ? ["adaptive_protection_config"] : []
│     ├────────────────
│     │ var.layer_7_ddos_defense_enable is null
│     │ var.type is "CLOUD_ARMOR_EDGE"
│ 
│ Error during operation: argument must not be null.
```

With these variables:
```
        name        = "second-test"
        type        = "CLOUD_ARMOR_EDGE"

        default_rule_action = "allow"

        layer_7_ddos_defense_enable = null
        recaptcha_redirect_site_key = null

        pre_configured_rules = {}
        security_rules = {}
        threat_intelligence_rules = {}
        custom_rules = {}
```

The `layer_7_ddos_defense_enable` variable is marked as optional AND unsuported for CLOUD_ARMOR_EDGE type in the documentation, but does not appear to be actually so.
Same problem with type CLOUD_ARMOR.

Regards,

**Comment by imrannayer** [comment]
@tanguynicolas u dont need to pass null values or empty maps. Those variables have default values and it should work without setting up in ur code.

**Comment by tanguynicolas** [comment]
I have no choice because I use the module with a loop (count) to be able to declare all my rules in the same place in the tfvars.
In the end, I simply put a default variable in the declaration of my policies, I didn't know it was possible to do so in a map. My mistake.

```
variable "policies" {
  type = list(object({
    name                                 = string
    ...
    layer_7_ddos_defense_enable          = optional(bool, false)
    ...
  }))
  description = "The security policies"
}
```

Thanks
