### ISSUE TITLE
removing security_rules tries to delete the policy and fails

### ISSUE THREAD

**Issue by romanvogman** [GoogleCloudPlatform/terraform-google-cloud-armor#59]
What I'm expecting to happened - Delete a specific rule from the rules in the policy, similar to how we can add/remove from the UI.

What happens - seems like terraform tries to delete and recreate the whole policy and fails.

After removing `security_rules` section, we're getting the following error when applying the changes:
`Error: Error waiting for Deleting SecurityPolicy: The security_policy resource '...' is already being used by '...'`

This means we need to remove the policy from being used by other resources each time we change a specific rules.

**Comment by imrannayer** [comment]
@romanvogman have you tried provider 4.76+ to solve the issue?

**Comment by romanvogman** [comment]
Hey @imrannayer,
We've set the provider to 4.76 and it's working as expected now. 

Thanks!
