### ISSUE TITLE
Unsupported argument error with 1.2.0 release

### ISSUE THREAD

**Issue by corey-hammerton** [GoogleCloudPlatform/terraform-google-cloud-armor#64]
I would like to
Report that we are experiencing Unsupported Argument errors with the newly released 1.2.0 version, the exact error string is in the below code block. 

In order to
Ensure the provider works as intended

Other Information:
Module version: 1.2.0
Provider version: v4.73.2

Cannot find this argument in the provider either: https://github.com/hashicorp/terraform-provider-google/blob/main/google/services/compute/resource_compute_security_policy.go

Error Message:
```
╷
│ Error: Unsupported argument
│
│   on .terraform/modules/cloud-armor/main.tf line 84, in resource "google_compute_security_policy" "policy":
│   84:       user_ip_request_headers = var.user_ip_request_headers
│
│ An argument named "user_ip_request_headers" is not expected here.
╵
```

**Comment by imrannayer** [comment]
@corey-hammerton It seems like it was released in 4.79 Beta provider.

https://github.com/hashicorp/terraform-provider-google-beta/blob/main/CHANGELOG.md

**Comment by corey-hammerton** [comment]
Is it planned for this module to only support the newest versions of the google-beta provider? Or to continue supporting the google provider?

**Comment by earzur** [comment]
just a question in that case, 

shouldn't the module's provider mark its dependency to a version higher than 4.80 using a `terraform.required_providers` block  ? That would have prevented to init with an incompatible provider, like i just did on our own projects...

```
terraform {
  required_version = ">= 1.5"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 4.80"
    }
  }
}
```

**Comment by imrannayer** [comment]
@earzur last PR should have also changed the min version required to 4.80 which would have triggered major release. Changing it now will not be helpful. In the meantime we can push a quick fix and update the README to reflect min version required to 4.80. Feel free
