### ISSUE TITLE
No option to turn on GraphQL parsing via TF

### ISSUE THREAD

**Issue by Nathan01110011** [GoogleCloudPlatform/terraform-google-cloud-armor#99]
Cloud Armor allows GraphQL parsing via the JSON parsing field -
![image](https://github.com/GoogleCloudPlatform/terraform-google-cloud-armor/assets/43985198/0c06e93f-0556-4ee3-a3a3-d72249d46780)

but `STANDARD_WITH_GRAPHQL` doesn't seem to be an option via TF

![image](https://github.com/GoogleCloudPlatform/terraform-google-cloud-armor/assets/43985198/7272146d-9382-4eff-88d6-8d4900dd1444)

Confirmed as `STANDARD_WITH_GRAPHQL` not working when in the `json_parsing` parameter in terraform deployment

**Comment by imrannayer** [comment]
@NathanOrr101 Module is not blocking the value. It seems like [provider](https://github.com/hashicorp/magic-modules/blob/86e74c75a61140817b17b38cdc40bbcc9dc6f69b/mmv1/third_party/terraform/services/compute/resource_compute_security_policy.go.erb#L439) is not accepting value other than STANDARD and DISABLED. Can you plz create enhancement request for the provider [here](https://github.com/hashicorp/terraform-provider-google/issues).

**Comment by NathanOrr101** [comment]
https://github.com/hashicorp/terraform-provider-google/issues/17039

Thanks.

**Comment by SarahFrench** [comment]
👋 Hi everyone, the provider was updated to allow using `STANDARD_WITH_GRAPHQL` that change should be released in v5.15.0 of the provider

**Comment by imrannayer** [comment]
Resolved in [v5.15](https://github.com/hashicorp/terraform-provider-google/blob/main/CHANGELOG.md#5150-feb-5-2024)
